06: 06.cpp
	g++ -std=c++14 -Wall -pedantic -Wextra -Wno-long-long 06.cpp
06d: 06.cpp
	g++ -std=c++14 -Wall -pedantic -Wextra -Wno-long-long -DDEBUG -g -ggdb 06.cpp
03: 03.cpp
	g++ -Wall -pedantic -Wextra -Wno-long-long 03.cpp
